package io.github.aedev.flow.player.stream

import android.util.Log
import io.github.aedev.flow.player.state.AudioTrackOption
import io.github.aedev.flow.player.state.SubtitleOption
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.extractor.stream.VideoStream

/**
 * Manages stream data processing - deduplication, sorting, and conversion.
 */
object StreamProcessor {
    
    private const val TAG = "StreamProcessor"
    
    /**
     * Process video streams - deduplicate and sort by height descending.
     */
    fun processVideoStreams(streams: List<VideoStream>): List<VideoStream> {
        return streams
            .distinctBy { it.getContent() }
            .sortedWith(
                compareByDescending<VideoStream> { VideoCodecUtils.qualityHeightFromStream(it) }
                    .thenBy { VideoCodecUtils.playbackCodecRank(it) }
                    .thenByDescending { it.bitrate }
            )
            .also { Log.d(TAG, "Processed ${streams.size} video streams -> ${it.size} unique") }
    }
    
    fun processAudioStreams(streams: List<AudioStream>): List<AudioStream> {
        return streams
            .sortedByDescending { it.averageBitrate }
            .groupBy { stream -> extractTrackLanguageKey(stream) }
            .map { (_, group) ->
                group.first()
            }
            .sortedBy { stream -> languageDisplayName(stream, 0) }
            .also { Log.d(TAG, "Processed ${streams.size} audio streams -> ${it.size} unique tracks") }
    }

    fun processSubtitleStreams(streams: List<SubtitlesStream>): List<SubtitlesStream> {
        return streams
            .filter { it.getContent().isNotBlank() }
            .distinctBy { stream ->
                listOf(
                    stream.getContent(),
                    stream.languageTag.orEmpty(),
                    stream.isAutoGenerated.toString(),
                    stream.format?.mimeType.orEmpty()
                ).joinToString("|")
            }
            .sortedWith(
                compareBy<SubtitlesStream> { it.isAutoGenerated }
                    .thenBy { it.displayLanguageName ?: it.languageTag ?: "" }
            )
            .also { Log.d(TAG, "Processed ${streams.size} subtitle streams -> ${it.size} unique tracks") }
    }

    /**
     * Derive a unique grouping key for deduplication. Uses audioTrackName, audioLocale, or
     * audioTrackId (trying both dot- and underscore-separated suffixes, then full ID) so that
     * tracks with formats like "A_hi" are not all collapsed into a single "default" group.
     */
    private fun extractTrackLanguageKey(stream: AudioStream): String {
        stream.audioTrackName?.takeIf { it.isNotBlank() }?.let { return it }
        stream.audioLocale?.language?.takeIf { it.isNotBlank() }?.let { return it }
        stream.audioTrackId?.let { id ->
            val dotPart = id.substringAfterLast(".").takeIf { it.isNotBlank() && it != id }
            if (dotPart != null) return dotPart
            val underPart = id.substringAfterLast("_").takeIf { it.isNotBlank() && it != id }
            if (underPart != null) return underPart
            return id
        }
        return "default"
    }

    /**
     * Derive a human-readable language display name from an AudioStream.
     * Priority: audioTrackName → audioLocale display language → parsed audioTrackId → fallback.
     */
    private fun languageDisplayName(stream: AudioStream, fallbackIndex: Int): String {
        stream.audioTrackName?.takeIf { it.isNotBlank() }?.let { return it }

        stream.audioLocale?.language?.takeIf { it.isNotBlank() }?.let { langCode ->
            val locale = java.util.Locale(langCode)
            val name = locale.getDisplayLanguage(java.util.Locale.getDefault())
            if (name.isNotBlank()) return name.replaceFirstChar { it.uppercase() }
        }

        stream.audioTrackId?.let { trackId ->
            val dotCode = trackId.substringAfterLast(".").takeIf { it.isNotBlank() && it != trackId }
            val underCode = trackId.substringAfterLast("_").takeIf { it.isNotBlank() && it != trackId }
            val langCode = dotCode ?: underCode
            if (langCode != null) {
                val locale = java.util.Locale(langCode)
                val name = locale.getDisplayLanguage(java.util.Locale.getDefault())
                if (name.isNotBlank() && !name.equals(langCode, ignoreCase = true)) {
                    return name.replaceFirstChar { it.uppercase() }
                }
            }
            return trackId.replaceFirstChar { it.uppercase() }
        }

        return "Track ${fallbackIndex + 1}"
    }
    
    /**
     * Convert audio streams to UI options.
     */
    fun toAudioTrackOptions(streams: List<AudioStream>): List<AudioTrackOption> {
        return streams.mapIndexed { index, stream ->
            AudioTrackOption(
                index = index,
                label = languageDisplayName(stream, index),
                language = stream.audioLocale?.displayLanguage
                    ?.takeIf { it.isNotBlank() }
                    ?: "",
                bitrate = stream.averageBitrate.coerceAtLeast(0).toLong()
            )
        }
    }
    
    /**
     * Convert subtitle streams to UI options.
     */
    fun toSubtitleOptions(subtitles: List<SubtitlesStream>): List<SubtitleOption> {
        return subtitles.map {
            val language = it.languageTag ?: it.locale?.toLanguageTag() ?: "Unknown"
            val baseLabel = it.displayLanguageName ?: language
            SubtitleOption(
                url = it.getContent(),
                language = language,
                label = if (it.isAutoGenerated) "$baseLabel (Auto)" else baseLabel,
                isAutoGenerated = it.isAutoGenerated
            )
        }
    }
}
