package io.github.aedev.flow.ui.components

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.animation.slideInVertically
import androidx.compose.animation.slideOutVertically
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.media3.common.Player
import androidx.media3.common.text.Cue
import androidx.media3.common.text.CueGroup
import io.github.aedev.flow.player.EnhancedPlayerManager

@Composable
fun Media3SubtitleOverlay(
    enabled: Boolean,
    isAutoGenerated: Boolean,
    style: SubtitleStyle = SubtitleStyle(),
    modifier: Modifier = Modifier
) {
    var cues by remember { mutableStateOf(emptyList<Cue>()) }
    val player = EnhancedPlayerManager.getInstance().getPlayer()

    DisposableEffect(player) {
        if (player == null) {
            onDispose { }
        } else {
            val listener = object : Player.Listener {
                override fun onCues(cueGroup: CueGroup) {
                    cues = cueGroup.cues
                }
            }
            player.addListener(listener)
            cues = player.currentCues.cues
            onDispose {
                player.removeListener(listener)
            }
        }
    }

    val displayText = remember(enabled, isAutoGenerated, cues) {
        if (!enabled) {
            null
        } else {
            cues.toSubtitleDisplayText(isAutoGenerated)
        }
    }

    val bottomPadding = style.bottomPadding.coerceIn(24f, 220f)

    AnimatedVisibility(
        visible = displayText != null,
        enter = fadeIn() + slideInVertically { it / 2 },
        exit = fadeOut() + slideOutVertically { it / 2 },
        modifier = modifier.fillMaxSize()
    ) {
        if (displayText != null) {
            Box(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(horizontal = 16.dp),
                contentAlignment = Alignment.BottomCenter
            ) {
                Surface(
                    color = style.backgroundColor,
                    shape = RoundedCornerShape(8.dp),
                    modifier = Modifier.offset(y = -bottomPadding.dp)
                ) {
                    Text(
                        text = displayText,
                        color = style.textColor,
                        fontSize = style.fontSize.sp,
                        fontWeight = if (style.isBold) FontWeight.Bold else FontWeight.Normal,
                        textAlign = TextAlign.Center,
                        lineHeight = (style.fontSize * 1.25f).sp,
                        modifier = Modifier.padding(horizontal = 12.dp, vertical = 6.dp)
                    )
                }
            }
        }
    }
}

private fun List<Cue>.toSubtitleDisplayText(isAutoGenerated: Boolean): String? {
    val textCues = mapNotNull { it.text?.toString()?.cleanCueText(isAutoGenerated) }
        .filter { it.isNotBlank() }
        .distinct()

    if (textCues.isEmpty()) return null

    return when (textCues.size) {
        1 -> textCues.first()
        else -> textCues.last()
    }.takeIf { it.isNotBlank() }
}

private fun String.cleanCueText(isAutoGenerated: Boolean): String {
    val lines = replace('\u00A0', ' ')
        .replace(Regex("[ \\t\\x0B\\f\\r]+"), " ")
        .lines()
        .map { it.trim() }
        .filter { it.isNotBlank() }

    if (lines.isEmpty()) return ""

    if (isAutoGenerated) {
        return lines.latestRollingCaptionLine()
    }

    return lines
        .takeLast(2)
        .joinToString("\n")
        .trim()
}

private fun List<String>.latestRollingCaptionLine(): String {
    if (size == 1) return first()

    val latestLine = last()
    val previousLine = this[size - 2]
    val previousWords = previousLine.splitWords()
    val latestWords = latestLine.splitWords()

    if (previousWords.isEmpty() || latestWords.isEmpty()) return latestLine

    val overlap = longestSuffixPrefixOverlap(previousWords, latestWords)
    val freshWords = latestWords.drop(overlap)

    return freshWords
        .takeIf { it.isNotEmpty() }
        ?.joinToString(" ")
        ?: latestLine
}

private fun String.splitWords(): List<String> {
    return split(Regex("\\s+")).filter { it.isNotBlank() }
}

private fun longestSuffixPrefixOverlap(previous: List<String>, latest: List<String>): Int {
    val maxOverlap = minOf(previous.size, latest.size)
    for (count in maxOverlap downTo 1) {
        val previousSuffix = previous.takeLast(count)
        val latestPrefix = latest.take(count)
        if (previousSuffix.equalsWords(latestPrefix)) {
            return count
        }
    }
    return 0
}

private fun List<String>.equalsWords(other: List<String>): Boolean {
    if (size != other.size) return false
    return indices.all { index ->
        this[index].trimPunctuation().equals(other[index].trimPunctuation(), ignoreCase = true)
    }
}

private fun String.trimPunctuation(): String {
    return trim { !it.isLetterOrDigit() }
}
